
server:
    port: 8182
    servlet:
      contextPath: /demo
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,application/json;charset=UTF-8

